import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, Share2 } from "lucide-react";
import { articles, getArticleBySlug } from "@/content/hub";
import {createMetadata} from "@/lib/seo";

export function generateStaticParams(){return articles.map(article=>({slug:article.slug}))}
export async function generateMetadata({params}){const {slug}=await params;const article=getArticleBySlug(slug);if(!article)return{};return createMetadata({title:article.title,description:article.excerpt,path:`/prime-hub/articles/${slug}`,image:article.image,type:"article",publishedTime:article.publishedAt})}
export default async function ArticlePage({params}){const {slug}=await params;const article=getArticleBySlug(slug);if(!article)notFound();const related=articles.filter(item=>item.slug!==slug).slice(0,2);const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,datePublished:article.publishedAt,author:{"@type":"Organization",name:article.author},publisher:{"@type":"Organization",name:"PrimeShow Entertainment"},description:article.excerpt};return <main id="main-content" className={`article-detail article-detail-${slug}`}><div className="reading-progress"/><section className="article-hero"><Image src={article.image} alt={article.title} fill priority sizes="100vw"/><div className="article-hero-shade"/><div className="container"><Link href="/prime-hub" className="back-link"><ArrowLeft/> Primeverse</Link><div className="eyebrow">{article.category} · {article.movie}</div><h1>{article.title}</h1><p>{article.excerpt}</p><div className="article-byline"><span>{article.author}</span><span>{new Date(article.publishedAt).toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}</span><span>{article.readingTime}</span></div></div></section><article className="article-body container"><aside aria-label="Table of contents"><span>In this story</span>{article.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}<button aria-label="Share this article"><Share2/> Share</button></aside><div>{article.sections.map((s,i)=><section id={s.id} key={s.id}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p>{i===0&&<blockquote>“Every department strengthens the same story.”</blockquote>}</section>)}</div></article><section className="section continue-exploring"><div className="container"><div className="eyebrow">Related stories</div><h2>Continue <em>reading.</em></h2><div className="continue-grid">{related.map(item=><Link href={`/prime-hub/articles/${item.slug}`} key={item.slug}><span>{item.category}</span><strong>{item.title}</strong><ArrowRight/></Link>)}</div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>}
