"use client";
import { useEffect } from "react";
import Script from "next/script";
import { ANALYTICS_EVENTS } from "@/lib/analytics/events";
export default function Analytics() {
  const gaId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID; const clarityId = process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID;
  useEffect(() => { const track = (name, parameters = {}) => window.gtag?.("event", name, parameters); const click = event => { const link = event.target?.closest?.("a,button"); if (!link) return; const href = link.getAttribute("href") || ""; const label = (link.textContent || link.getAttribute("aria-label") || "").trim().slice(0, 80); if (/wa\.me|whatsapp/i.test(href)) track(ANALYTICS_EVENTS.WHATSAPP_CLICK, { link_text: label }); else if (/youtube/i.test(href)) track(ANALYTICS_EVENTS.VIDEO_INTERACTION, { action: "open", link_text: label }); else if (link.classList.contains("button")) track(ANALYTICS_EVENTS.CTA_CLICK, { link_text: label, link_url: href }); }; const depths = new Set(); const scroll = () => { const max = document.documentElement.scrollHeight - innerHeight; if (max <= 0) return; const percent = Math.round((scrollY / max) * 100); [25,50,75,90].forEach(depth => { if (percent >= depth && !depths.has(depth)) { depths.add(depth); track(ANALYTICS_EVENTS.SCROLL_DEPTH, { percent_scrolled: depth }); } }); }; const custom = event => { const detail = event.detail || {}; track(detail.name || "site_interaction", detail); }; document.addEventListener("click", click, { passive: true }); addEventListener("scroll", scroll, { passive: true }); addEventListener("prime-analytics", custom); return () => { document.removeEventListener("click", click); removeEventListener("scroll", scroll); removeEventListener("prime-analytics", custom); }; }, []);
  return <>{gaId ? <><Script src={`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(gaId)}`} strategy="lazyOnload"/><Script id="ga4" strategy="lazyOnload">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config',${JSON.stringify(gaId)},{anonymize_ip:true});`}</Script></> : null}{clarityId ? <Script id="clarity" strategy="lazyOnload">{`(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src='https://www.clarity.ms/tag/'+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,'clarity','script',${JSON.stringify(clarityId)});`}</Script> : null}</>;
}
