export const aboutContent = {
  navigation: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about" },
    { label: "Features", href: "/services" },
    { label: "Primeverse", href: "/#primeverse" },
  ],
  chapters: [
    {
      id: "about-primeshow",
      number: "01",
      eyebrow: "The story begins",
      title: <>Stories are where <em>we begin.</em></>,
      body: "PrimeShow Entertainment brings creative ambition, production intelligence, and audience insight together to shape Indian stories for the world.",
      quote: "From the first spark to the final frame, every choice serves the story.",
      image: "/images/about/chapter-01-story-first.webp",
      imageAlt: "A creative film team developing a story in a global planning room",
      layout: "split",
    },
    {
      id: "vision",
      number: "02",
      eyebrow: "Our vision",
      title: <>Indian imagination.<br /><em>Without borders.</em></>,
      body: "To become a globally trusted home for distinctive Indian cinema—where brave ideas find world-class craft, scale, and audiences everywhere.",
      quote: "We see a future where the place a story begins never limits how far it can travel.",
      image: "/images/hero-studio.webp",
      imageAlt: "A vast film studio illuminated by warm lights beyond a cinema camera",
      layout: "vision",
    },
    {
      id: "mission",
      number: "03",
      eyebrow: "Our mission",
      title: <>Protect the idea.<br /><em>Elevate every frame.</em></>,
      body: "We unite storytellers, craftspeople, production systems, distribution thinking, and technology around one purpose: creating films that move audiences and endure beyond opening weekend.",
      quote: "Creative courage, executed with clarity.",
      image: "/images/about/chapter-03-elevate.webp",
      imageAlt: "A large-scale Indian film scene being captured with professional cinema cameras",
      layout: "reverse",
    },
    {
      id: "strength",
      number: "04",
      eyebrow: "Our strength",
      title: <>One ecosystem.<br /><em>Every advantage.</em></>,
      body: "Creative and commercial capabilities designed to move a story confidently from development to audiences.",
      layout: "strength",
    },
  ],
  strengths: [
    { icon: "MapPinned", title: "Pan-India Reach", text: "Stories positioned for audiences across regions and languages." },
    { icon: "Award", title: "Recognised Storytelling", text: "Creative ambition supported by exacting craft and execution." },
    { icon: "Sparkles", title: "Creative Excellence", text: "Distinctive ideas developed with clarity and conviction." },
    { icon: "Clapperboard", title: "Production Expertise", text: "Integrated planning from development through final delivery." },
    { icon: "Network", title: "Distribution Network", text: "Strategic thinking that connects films with their audiences." },
    { icon: "Projector", title: "Exhibition Capability", text: "A big-screen perspective embedded in every release decision." },
    { icon: "Handshake", title: "Industry Partnerships", text: "Long-term collaboration built on trust and shared ambition." },
    { icon: "Cpu", title: "Technical Innovation", text: "Modern tools and workflows in service of better storytelling." },
  ],
};
