export const movies = [
  {
    slug: "hanuman",
    title: "HanuMan",
    year: "2024",
    releaseDate: "2024-01-12",
    language: "Telugu",
    languages: ["Telugu", "Hindi", "Tamil", "Kannada", "Malayalam"],
    genre: "Superhero · Fantasy",
    duration: "2h 38m",
    status: "Released",
    division: ["production", "distribution"],
    territory: "Pan India",
    posterPosition: "0%",
    poster: "/images/posters/hanuman.webp",
    distributionPoster: "/images/distribution/hanuman.webp",
    posterFocalPoint: "center center",
    heroImage: "/images/hero-hanuman-optimized.webp",
    heroFocalPoint: "center center",
    gallery: [
      {
        image: "/images/movies/hanuman/gallery-1.webp",
        alt: "HanuMan character standing before the Indian flag",
        focalPoint: "center center",
      },
      {
        image: "/images/movies/hanuman/gallery-2.webp",
        alt: "Mythic HanuMan sequence above a glowing cloudscape",
        focalPoint: "center center",
      },
      {
        image: "/images/movies/hanuman/gallery-3.webp",
        alt: "Anjanadri action scene before the monumental Hanuman statue",
        focalPoint: "center center",
      },
    ],
    synopsis: "In the imagined world of Anjanadri, an unlikely hero discovers a mysterious power and must rise to protect his people.",
    trailer: {
      title: "HanuMan Official Trailer — Telugu",
      url: "https://www.youtube.com/playlist?list=PL5gQyq_32RZKeCy3psuFl2-f8LyXXvRnD",
      duration: "3:29",
    },
    cast: ["Teja Sajja", "Amritha Aiyer", "Varalaxmi Sarathkumar", "Vinay Rai"],
    crew: ["Prasanth Varma — Writer & Director", "K. Niranjan Reddy — Producer"],
    awards: ["National recognition across two categories"],
    facts: ["Designed as a multilingual theatrical experience", "Set in the fictional world of Anjanadri"],
    featured: true,
  },
  {
    slug: "syg",
    title: "Sambarala Yeti Gattu",
    year: "TBA",
    releaseDate: null,
    language: "Multilingual",
    languages: ["Telugu", "Hindi"],
    genre: "Feature Film",
    duration: "TBA",
    status: "Post Production",
    division: ["production"],
    territory: "Pan India",
    posterPosition: "20%",
    poster: "/images/posters/syg.webp",
    posterFocalPoint: "center center",
    heroImage: "/images/hero-syg-optimized.webp",
    heroFocalPoint: "center center",
    gallery: [
      {
        image: "/images/movies/syg/gallery-1.webp",
        alt: "SYG character standing amid a sunlit red-dust gathering",
        focalPoint: "center center",
      },
      {
        image: "/images/movies/syg/gallery-2.webp",
        alt: "SYG character with cattle in a rustic village setting",
        focalPoint: "center 38%",
      },
      {
        image: "/images/movies/syg/gallery-3.webp",
        alt: "SYG character addressing a gathered village crowd",
        focalPoint: "center center",
      },
    ],
    synopsis: "A PrimeShow project currently in post-production. Official story details will be revealed by the studio.",
    trailer: {
      title: "SYG — Sambarala Yeti Gattu Carnage",
      url: "https://www.youtube.com/watch?v=WrwcrBfZWmY",
      duration: "Official Teaser",
    },
    cast: [], crew: [], awards: [], facts: [], featured: true,
  },
  {
    slug: "brb",
    title: "Billa Ranga Baasha",
    year: "TBA",
    releaseDate: null,
    language: "Multilingual",
    languages: ["Telugu", "Hindi", "Kannada"],
    genre: "Feature Film",
    duration: "TBA",
    status: "In Production",
    division: ["production"],
    territory: "Pan India",
    posterPosition: "40%",
    poster: "/images/posters/brb-optimized.webp",
    posterFocalPoint: "center center",
    heroImage: "/images/hero-brb-optimized.webp",
    heroFocalPoint: "center center",
    gallery: [
      {
        image: "/images/movies/brb/gallery-1.webp",
        alt: "BRB character in expedition goggles against an icy mountain fortress",
        focalPoint: "center center",
      },
      {
        image: "/images/movies/brb/gallery-2.webp",
        alt: "BRB warrior standing before a fiery emblem and frozen battleground",
        focalPoint: "center center",
      },
      {
        image: "/images/movies/brb/gallery-3.webp",
        alt: "BRB character in a red jacket crossing a ruined battlefield",
        focalPoint: "center 30%",
      },
    ],
    synopsis: "A PrimeShow story currently in production. Cast, crew, and release information will be published following the official announcement.",
    trailer: {
      title: "Billa Ranga Baasha — First Blood",
      url: "https://www.youtube.com/watch?v=1ur1ZLlCj_M",
      duration: "Concept Teaser",
    },
    cast: [], crew: [], awards: [], facts: [], featured: true,
  },
  {
    slug: "darling",
    title: "Darling",
    year: "TBA",
    releaseDate: null,
    language: "Telugu",
    languages: ["Telugu"],
    genre: "Romance · Drama",
    duration: "TBA",
    status: "Released",
    division: ["production"],
    territory: "India",
    posterPosition: "60%",
    poster: "/images/posters/darling.webp",
    posterFocalPoint: "center center",
    hasDetailPage: false,
    synopsis: "A PrimeShow production. Official story, cast, crew, and release details will be announced by the studio.",
    trailer: null,
    cast: [], crew: [], awards: [], facts: [], featured: true,
  },
  {
    slug: "house-arrest",
    title: "House Arrest",
    year: "TBA",
    releaseDate: null,
    language: "Telugu",
    languages: ["Telugu"],
    genre: "Comedy · Family",
    duration: "TBA",
    status: "Released",
    division: ["production"],
    territory: "India",
    posterPosition: "80%",
    poster: "/images/posters/house-arrest.webp",
    posterFocalPoint: "center center",
    hasDetailPage: false,
    synopsis: "A PrimeShow production. Official story, cast, crew, and release details will be announced by the studio.",
    trailer: null,
    cast: [], crew: [], awards: [], facts: [], featured: true,
  },
  {
    slug: "bfh",
    title: "BFH",
    year: "TBA",
    releaseDate: null,
    language: "Telugu",
    languages: ["Telugu"],
    genre: "Feature Film",
    duration: "TBA",
    status: "Released",
    division: ["production"],
    territory: "India",
    posterPosition: "100%",
    poster: "/images/posters/bfh.webp",
    posterFocalPoint: "center center",
    hasDetailPage: false,
    synopsis: "A PrimeShow production. Official story, cast, crew, and release details will be announced by the studio.",
    trailer: null,
    cast: [], crew: [], awards: [], facts: [], featured: true,
  },
  ...[
    ["pushpa", "Pushpa", "2021", "Pan India", "/images/distribution/pushpa.webp"],
    ["rrr", "RRR", "2022", "Pan India", "/images/distribution/rrr.webp"],
    ["dj-tillu", "DJ Tillu", "2022", "Regional", "/images/distribution/dj-tillu.webp"],
    ["sarkaru-vaari-paata", "Sarkaru Vaari Paata", "2022", "Regional", "/images/distribution/sarkaru-vaari-paata.webp"],
    ["bro", "BRO", "2023", "Regional", "/images/distribution/bro.webp"],
    ["kushi", "Kushi", "2023", "Regional", "/images/distribution/kushi.webp"],
    ["bheemla-nayak", "Bheemla Nayak", "2022", "Regional", "/images/distribution/bheemla-nayak.webp"],
    ["dhamaka", "Dhamaka", "2022", "Regional", "/images/distribution/dhamaka.webp"],
    ["manjumal-boys", "Manjumal Boys", "2024", "Regional", "/images/distribution/manjumal-boys.webp"],
  ].map(([slug, title, year, territory, distributionPoster]) => ({
    slug,
    title,
    year,
    releaseDate: null,
    language: "Telugu",
    languages: ["Telugu"],
    genre: "Feature Film",
    duration: "—",
    status: "Released",
    division: ["distribution"],
    territory,
    distributionPoster,
    hasDetailPage: false,
    synopsis: "PrimeShow distribution catalog title.",
    trailer: null,
    cast: [], crew: [], awards: [], facts: [], featured: false,
    isCatalogPlaceholder: true,
  })),
];

export const getMovieBySlug = (slug) => movies.find((movie) => movie.slug === slug);
export const productionMovies = movies.filter((movie) => movie.division.includes("production"));
export const distributionMovies = movies.filter((movie) => movie.division.includes("distribution"));
