"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ArrowDown, ArrowRight, Award, Camera, ChevronLeft, ChevronRight, Film, Play, Search, Sparkles, Trophy, X } from "lucide-react";
import SiteHeader from "@/components/layout/SiteHeader";
import SiteFooter from "@/components/layout/SiteFooter";
import ButtonLink from "@/components/ui/ButtonLink";

const tabs=["Articles","Movie Quizzes","Behind the Scenes","Upcoming Projects","Awards & Recognition"];

export default function PrimeHub({content,navigation}) {
  const root=useRef(null); const swipeStart=useRef(null); const [active,setActive]=useState(tabs[0]); const [query,setQuery]=useState(""); const [lightbox,setLightbox]=useState(null);
  const featuredQuizHref=content.quizzes[0]?`/prime-hub/quizzes/${content.quizzes[0].slug}`:"#quizzes";
  useEffect(()=>{
    const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
    const mobile=matchMedia("(max-width: 900px)").matches;
    if(reduced||mobile) return;
    gsap.registerPlugin(ScrollTrigger);
    const ctx=gsap.context(()=>{
      gsap.utils.toArray("[data-hub-reveal]").forEach(el=>gsap.fromTo(el,{y:38,opacity:0},{y:0,opacity:1,duration:.8,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 88%"}}));
    },root);
    return()=>{ctx.revert()};
  },[]);
  useEffect(()=>{const onKey=e=>{if(lightbox===null)return;if(e.key==="Escape")setLightbox(null);if(e.key==="ArrowRight")setLightbox((lightbox+1)%content.galleries.length);if(e.key==="ArrowLeft")setLightbox((lightbox-1+content.galleries.length)%content.galleries.length)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[lightbox,content.galleries.length]);
  const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return [
    ...content.articles.map(x=>({type:"Article",title:x.title,meta:x.category,href:`/prime-hub/articles/${x.slug}`})),
    ...content.quizzes.map(x=>({type:"Quiz",title:x.movie,meta:`${x.questions.length} questions`,href:`/prime-hub/quizzes/${x.slug}`})),
    ...content.upcomingProjects.map(x=>({type:"Movie",title:x.title,meta:x.status,href:`/movies/${x.slug}`})),
    ...content.awards.map(x=>({type:"Award",title:x.movie,meta:x.category,href:"#awards"})),
  ].filter(x=>(x.title+" "+x.meta+" "+x.type).toLowerCase().includes(q))},[query,content]);
  const switchTab=tab=>{setActive(tab);document.getElementById("hub-content")?.scrollIntoView({behavior:matchMedia("(max-width: 900px)").matches?"auto":"smooth",block:"start"})};
  return <div ref={root} className="site-wrap hub-theme"><SiteHeader items={navigation} activeHref="/prime-hub" className="hub-header"/><main id="main-content">
    <section className="hub-hero"><Image src="/images/hero-studio.webp" alt="Cinematic production studio for Primeverse" fill priority sizes="100vw"/><div className="hub-hero-shade"/><div className="grain"/><motion.div className="container hub-hero-copy" initial={{opacity:0,y:42}} animate={{opacity:1,y:0}} transition={{duration:.9}}><div className="eyebrow"><Sparkles size={15}/> The stories behind the stories</div><h1>PRIME<em>VERSE</em></h1><p>Where Stories Continue Beyond the Screen.</p><div className="hero-actions"><ButtonLink href="#hub-content">Explore Articles</ButtonLink><ButtonLink href={featuredQuizHref} variant="glass">Play Movie Quiz</ButtonLink></div></motion.div><a className="scroll-cue" href="#hub-content">Enter Primeverse <ArrowDown size={16}/></a></section>
    <section className="hub-nav-stage" id="hub-content"><div className="container"><div className="hub-search-wrap"><label className="hub-search"><Search/><span className="sr-only">Search Primeverse</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search movies, articles, awards and quizzes"/></label>{query&&<div className="hub-search-results" role="status">{results.length?results.map((r,i)=><Link key={`${r.type}-${i}`} href={r.href} onClick={()=>setQuery("")}><span>{r.type}</span><strong>{r.title}</strong><small>{r.meta}</small><ArrowRight/></Link>):<p>No results found.</p>}</div>}</div><div className="hub-tabs" role="tablist" aria-label="Primeverse sections">{tabs.map(tab=><button key={tab} role="tab" aria-selected={active===tab} className={active===tab?"active":""} onClick={()=>switchTab(tab)}>{tab}</button>)}</div></div></section>
    <AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-24}} transition={{duration:.45}}>
      {active==="Articles"&&<Articles items={content.articles}/>} {active==="Movie Quizzes"&&<Quizzes items={content.quizzes}/>} {active==="Behind the Scenes"&&<Gallery items={content.galleries} onOpen={setLightbox}/>} {active==="Upcoming Projects"&&<Upcoming items={content.upcomingProjects}/>} {active==="Awards & Recognition"&&<Awards items={content.awards}/>} 
    </motion.div></AnimatePresence>
    <section className="section continue-exploring"><div className="container"><div className="eyebrow">Continue exploring</div><h2>Your next story<br/><em>is already waiting.</em></h2><div className="continue-grid"><Link href="/movies/hanuman"><Film/><span>Watch & discover</span><strong>HanuMan</strong><ArrowRight/></Link><Link href="/prime-hub/articles/building-the-world-of-hanuman"><Camera/><span>Read the craft</span><strong>Behind Anjanadri</strong><ArrowRight/></Link><Link href="/prime-hub/quizzes/hanuman-ultimate-fan"><Trophy/><span>Test your fandom</span><strong>HanuMan Quiz</strong><ArrowRight/></Link></div></div></section>
  </main><SiteFooter />
  <AnimatePresence>{lightbox!==null&&<motion.div className="hub-lightbox" role="dialog" aria-modal="true" aria-label={content.galleries[lightbox].title} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onTouchStart={event=>{const touch=event.changedTouches[0];swipeStart.current={x:touch.clientX,y:touch.clientY}}} onTouchEnd={event=>{if(!swipeStart.current)return;const touch=event.changedTouches[0],dx=swipeStart.current.x-touch.clientX,dy=swipeStart.current.y-touch.clientY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.25)setLightbox((lightbox+(dx>0?1:-1)+content.galleries.length)%content.galleries.length);swipeStart.current=null}}><button className="lightbox-close" onClick={()=>setLightbox(null)} aria-label="Close gallery"><X/></button><button onClick={()=>setLightbox((lightbox-1+content.galleries.length)%content.galleries.length)} aria-label="Previous image"><ChevronLeft/></button><figure><Image src={content.galleries[lightbox].image} alt={content.galleries[lightbox].title} fill sizes="90vw" style={{objectPosition:content.galleries[lightbox].position}}/><figcaption><strong>{content.galleries[lightbox].title}</strong><span>{content.galleries[lightbox].caption}</span></figcaption></figure><button onClick={()=>setLightbox((lightbox+1)%content.galleries.length)} aria-label="Next image"><ChevronRight/></button></motion.div>}</AnimatePresence></div>;
}

function SectionHead({eyebrow,title,body}){return <div className="section-head" data-hub-reveal><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><p>{body}</p></div>}
function Articles({items}){return <section className="section hub-section"><div className="container"><SectionHead eyebrow="PrimeShow editorial" title={<>Stories <em>inside the frame.</em></>} body="Craft, culture, releases, and the people moving each story forward."/><div className="article-magazine">{items.map((a,i)=><Link className={`article-card article-${i+1}`} href={`/prime-hub/articles/${a.slug}`} key={a.slug}><div className="article-image"><Image src={a.image} alt={a.title} fill sizes="(max-width:700px) 100vw, 55vw" style={{objectPosition:i===1?"28% center":"center"}}/></div><div className="article-copy"><div><span>{a.category}</span><small>{new Date(a.publishedAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})} · {a.readingTime}</small></div><h3>{a.title}</h3><p>{a.excerpt}</p><b>Read story <ArrowRight/></b></div></Link>)}</div></div></section>}
function Quizzes({items}){return <section id="quizzes" className="section hub-section"><div className="container"><SectionHead eyebrow="Signature fan experience" title={<>How well do you<br/><em>know the story?</em></>} body="Five questions. One score. A new reason to return to the films you love."/><div className="quiz-library">{items.map(q=><Link className="quiz-card" href={`/prime-hub/quizzes/${q.slug}`} key={q.slug}><div className="quiz-poster" style={{"--poster-image":`url('${q.image}')`,"--poster-focus":q.posterFocalPoint}}><span className="quiz-play"><Play fill="currentColor"/></span></div><div><span>{q.difficulty} difficulty</span><h3>{q.movie}</h3><p>{q.questions.length} questions · Highest score saved on this device</p><b>Play quiz <ArrowRight/></b></div></Link>)}</div></div></section>}
function Gallery({items,onOpen}){return <section className="section hub-section"><div className="container"><SectionHead eyebrow="Behind the scenes" title={<>The making is<br/><em>part of the magic.</em></>} body="Sets, crews, equipment, and candid moments from the work beyond the frame."/><div className="hub-masonry">{items.map((g,i)=><button key={g.id} className={`hub-gallery-${i+1}`} onClick={()=>onOpen(i)} aria-label={`Open ${g.title}`}><Image src={g.image} alt={g.title} fill sizes="(max-width:700px) 100vw, 45vw" style={{objectPosition:g.position}}/><span><strong>{g.title}</strong><small>{g.caption}</small></span></button>)}</div></div></section>}
function Upcoming({items}){return <section className="section hub-section"><div className="container"><SectionHead eyebrow="Coming from PrimeShow" title={<>New worlds<br/><em>in the making.</em></>} body="Verified announcements and official production updates will appear here first."/><div className="upcoming-grid">{items.map(item=><Link key={item.slug} href={`/movies/${item.slug}`} className="upcoming-card"><div className="upcoming-art" style={{"--poster-image":`url('${item.poster}')`,"--poster-focus":item.posterFocalPoint}}><span className="status">{item.status}</span></div><div><small>Expected {item.expectedRelease}</small><h3>{item.title}</h3><p>{item.synopsis}</p><b>Project details <ArrowRight/></b></div></Link>)}</div></div></section>}
function Awards({items}){return <section id="awards" className="section hub-section"><div className="container"><SectionHead eyebrow="Awards & recognition" title={<>Milestones that<br/><em>move us forward.</em></>} body="A verified studio archive for awards, selections, box-office milestones, and industry recognition."/><div className="award-timeline">{items.map(item=><article key={item.id}><span className="award-year">{item.year}</span><div className="award-icon"><Award/></div><div><small>{item.category}</small><h3>{item.movie}</h3><p>{item.description}</p></div></article>)}<article className="award-pending"><span className="award-year">NEXT</span><div className="award-icon"><Sparkles/></div><div><small>The archive continues</small><h3>Future recognition</h3><p>New verified achievements will be added through the Primeverse content system.</p></div></article></div></div></section>}
